### ISSUE TITLE
[FEATURE]ability to use bot for non PS2 events

### ISSUE THREAD

**Issue by CuchCuchCuch** [Combustiblemon/Discord-Event-Bot#46]
ability to use bot for non PS2 events

im thinking for spacemen

could be nearly the same, just need something to track amount of people, not what they want to play as
as well as letting people know when event is

**Comment by Combustiblemon** [comment]
Functionality already exists. Consider using `$event Training`

![image](https://user-images.githubusercontent.com/25153716/87848319-b94c3000-c8e7-11ea-859e-cb54b9a17e73.png)
