### ISSUE TITLE
Statistical Analysis per OPS night per Signup [FEATURE]

### ISSUE THREAD

**Issue by LivingLabDev** [Combustiblemon/Discord-Event-Bot#47]
**Is your feature request related to a problem? Please describe.**
1) gathering statistics about the ops night in terms of " metrics here " Gives us an objective few on how well the outfit performed, how well the leaders preformed and how well individual soldiers performed. It enables us to make accurate reporting and realise how well our outfit is doing when we cooperate together. 

As a platoon leader, I would like to see how well each of my squads (as a group) did so I know which kind of combat action was I should repeat in the future.
As a trainer in the outfit, I would like to identify squad leaders and squad members that need additionally training so that I can do a targeted intervention.

As a recruitment officer I would like to see what kind of soldiers we need to improve our outfit so that we can better motivate them to join our outfit.

As an squad leader, I would like to be able to see who is good and what role so I can make more balanced squad compositions that enable me to win battles more consistently. 
As an outfit leader, I would like to know how well the outfit is progressing over time so I know if I need to do more management.
As a squad leader I would like to see how well each of my members did in my squad so I know which members need more personal attention.
As a soldier in the ops night I would like to know how I did compared to others so I know if I still have to improve or not.
As a soldier in the ops night I would like to know how well others did so that I get motivated to better next time (competitiveness).

**Describe the solution you'd like**

A reporting tool (which can come in the form of a bot) that gathers information about the individual members of BRTD that sign up for an event for the duration of the OPS.
This tool should then give the following information:
K/D ratio, Healing done, Capture bases, #of kills, #of deaths, (rate of fire if possible), gun used.
It should then combine that per squad; Bravo squad, alpha, etc.
It should clearly list the squad leader of that squad.
It should state who was the platoonleader of the platoon.
It should store this information so it can be compared to the next event.

**Describe alternatives you've considered**
I’ve tried Grafina, but I can’t get the API to connect to the planetside 2 universe. I’ve tried planetside universe but it cannot specify a “window of time” so I only get general information.
Making a data excerpt of the planetside 2 universe and then comparing that at the end of the ops. 
**Additional context**

**Comment by Combustiblemon** [comment]
Haresus is doing that every OP
